### PR TITLE
Rework script and add 64bit support

### PR DESCRIPTION
**Pull request by NeroBurner**
I've created myself a script to change between 64bit and 32bit mode. Each mode has its own bugs, so switching between the modes is beneficial for me.

I've made the script very modular. Each command (like installing packages with winetricks, or creating a default warframe config, or updating the registry) can be invoked separately. To not have to specify that many command line flags the helper flags `--install` and `--install-system` are added.

Some things I added to the script:
- add 64bit support (use same game directory, but differen wine prefix)
- add flags to open `winecfg` or `regedit` inside the warframe wine prefix
- add overrides for `download_dir` and `wine_prefix_base`, which are replaced in the installed script (when copied to `/usr/bin/warframe`). This means one can install the script with user defined paths
- flag `--install` creates and prepares the wine-prefix, creates the default config for warframe and updates the registry
- flag `--install-system` copies the script to `/usr/bin/warframe` and creates menu and desktop shortcuts
- flag `--update` does the same thing as `Warframe-Launcher.bat` did

To see the full set of options run `./warframe.sh --help`
```
./warframe.sh [options]

options:
    --download-dir      override default download_dir variable
    --wine-prefix-dir   override default wine_prefix_base variable
    --winecfg           start winecfg with the current wine bottle
    --regedit           start regedit with the current wine bottle
    -w, --winetricks    install packages to wine bottle, don't launch game
    -r, --registry      update wine registry, don't launch game
    -c, --config        create basic warframe configuration file inside wine bottle
    -i, --install       same as defining
                        '--winetricks --registry and --config
    --install-bin       install script to /usr/bin (uses sudo for root access).
                        Replaces 'download_dir' and 'wine_prefix_base' with
                        overrides.
    --menu-shortcut     create menu entry (uses sudo for root access)
    --desktop-shortcut  create desktop shortcut (requires --menu-shortcut
                        for installation of warframe icon)
    --install-system    same as defining
                        '--install-bin --menu-shortcut and --desktop-shortcut'
    --uninstall-system  remove all the files installed by --install-system
    -u, --update        use Warframe executable to update downloaded game files.
                        Use when launcher fails to update the files.
    --32bit             use 32bit wine bottle and 32bit Warframe
    -v, --verbose       print each executed command
    -h, --help          print this help message and quit
```

I hope that we can merge our efforts and have more time to play this awesome game :)

### CODE REVIEW

**Comment by NeroBurner** [comment]
a few updates:
- fix download_dir variable
- add overrides for video ram and email (used in `--install-bin` which installs the script to `/usr/bin/warframe`
- when the flag `--verbose` is set then don't set `WINEDEBUG=-all` to get error messages or other wine messages

**Comment by GloriousEggroll** [comment]
Sorry I know this is a bit late. I haven't updated this or merged any changes for a couple reasons:

1. I have built a new updater bash script that no longer needs the Warframe.msi at all. Hell you don't even need the launcher. This will make Warframe-Launcher.bat obsolete. 

2. I don't want so many options, I want the script to be simple to use for people, and for them to not have to use a command every time they want to change something. The prefix is set to 64 bit and DX11 mode now, as DX9 has missing textures and 32 bit has max memory problems.

3. I want the script to be compatible with Lutris. In order for that to work it needed to have the batch script or an EXE. The new launch script will copy itself as an EXE. It will also use curl, making the need for wget obsolete

4. The EE.cfg and wf.reg files are needed for lutris install scripts, this is why I did not make them generate in my install script.

Please see updater.sh, as this will basically be the new warframe launcher for linux, replacing Warframe-Launcher.bat, Warframe.msi, Launcher.exe, and any registry settings involved with the previous launcher.

**Comment by NeroBurner** [comment]
Awesome for implementing the updater without the Warframe exe. Hope this fixed the vanishing downloaded folders. 

I'm a command line junky. And I implemented most of the options so I can change portions of the install without having to do all of the install steps. And also a way to directly launch Warframe after a crash without redownloading MSI file an run updater. I will check out your new implementation. If it is fast enough I don't need a non-update launch option :)

**Comment by GloriousEggroll** [comment]
going to go ahead and close this for now. what I could use is an option to optimize the cache if you get around to it before i do. the command should be

Warframe.exe -silent -log:/Preprocessing.log -dx10:1 -dx11:1 -threadedworker:1 -cluster:public -language:en -applet:/EE/Types/Framework/CacheDefraggerAsync /Tools/CachePlan.txt

**Pull request closed without merging**
